# Site settings

title: Siddharth Singh
description: 'D&nbsp;e&nbsp;v&nbsp;O&nbsp;p&nbsp;s&nbsp;&nbsp;|&nbsp;&nbsp;F&nbsp;O&nbsp;S&nbsp;S'
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techieatheart.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: matthiaslischka/jekyll-uno  

author:
  name: 'Siddharth Singh'
  email: s.sid0401@gmail.com
  github_username:  techieatheart
  linkedin_username:  singhsid01
  #twitter_username: matthiaslischka

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  
# exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
